---
- name: "Verify"
  hosts: "all"
  gather_facts: false
  become: true

  vars:
    pgadmin_docker_name: "pgadmin"
    pgadmin_docker_conf_dir: "/etc/pgadmin"

  tasks:
    - name: "Check for config file"
      ansible.builtin.stat:
        path: "{{ pgadmin_docker_conf_dir }}/servers.json"
      register: "_servers_json_stat"

    - name: "Verify config file exists"
      ansible.builtin.assert:
        that: "_servers_json_stat.stat.exists"

    - name: "Load servers.json"
      ansible.builtin.slurp:
        src: "{{ pgadmin_docker_conf_dir }}/servers.json"
      register: _servers_json

    - name: "Convert severs.json to Ansible yaml"
      ansible.builtin.set_fact:
        _servers_yml: "{{ _servers_json['content'] | b64decode | from_json }}"

    - name: "Debug"
      ansible.builtin.debug:
        msg: "{{ _servers_yml['Servers']['pg_two'] }}"

    - name: "Verify contents of servers.json"
      ansible.builtin.assert:
        that:
          - "_servers_yml['Servers']['pg_one'] is defined"
          - "_servers_yml['Servers']['pg_two'] is defined"
          - "_servers_yml['Servers']['pg_one']['host'] == 'pgone.example.com'"
          - "_servers_yml['Servers']['pg_two']['host'] == 'pgtwo.example.com'"
